CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100

DATA_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_TOKEN = "<image>"

DATA_VIDEO_TOKEN = "<video>"
DEFAULT_VIDEO_TOKEN = "<image>"